from django.conf import settings

DEFAULT_SETTINGS = {
    "SHAPEFILES_DIR": 'data/shapefiles',
    "GEOMETRY_COLUMN": 'shape',
    "API_DOMAIN": '/',
    "API_PREFIX": 'boundaries/',
} | getattr(settings, 'BOUNDARY_SVC_SETTINGS', {})
SHAPEFILES_DIR = DEFAULT_SETTINGS["SHAPEFILES_DIR"]
GEOMETRY_COLUMN = DEFAULT_SETTINGS["GEOMETRY_COLUMN"]
API_DOMAIN = DEFAULT_SETTINGS["API_DOMAIN"]
API_PREFIX = DEFAULT_SETTINGS["API_PREFIX"]